#nullable enable
namespace DistortionCorrection.UI;

partial class BatchWarpPage
{
    private System.ComponentModel.IContainer? components = null;
    private TableLayoutPanel layoutPanel = null!;
    private Label calibrationLabel = null!;
    private TextBox calibrationPathTextBox = null!;
    private Button browseCalibrationButton = null!;
    private Label inputLabel = null!;
    private TextBox inputFolderTextBox = null!;
    private Button browseInputButton = null!;
    private Label outputLabel = null!;
    private TextBox outputFolderTextBox = null!;
    private Button browseOutputButton = null!;
    private Label placementLabel = null!;
    private ComboBox placementComboBox = null!;
    private CheckBox recursiveCheckBox = null!;
    private Label fixedLabel = null!;
    private FlowLayoutPanel fixedPanel = null!;
    private Label fixedXLabel = null!;
    private NumericUpDown fixedXNumeric = null!;
    private Label fixedYLabel = null!;
    private NumericUpDown fixedYNumeric = null!;
    private Button startButton = null!;
    private ProgressBar progressBar = null!;
    private Label statusLabel = null!;
    private Label helpLabel = null!;
    private GroupBox centeredContentGroupBox = null!;
    private FlowLayoutPanel centeredContentPanel = null!;
    private Label centeredInputSizeLabel = null!;
    private NumericUpDown centeredInputWidthNumeric = null!;
    private Label centeredInputTimesLabel = null!;
    private NumericUpDown centeredInputHeightNumeric = null!;
    private Label centeredOutputSizeLabel = null!;
    private NumericUpDown centeredOutputWidthNumeric = null!;
    private Label centeredOutputTimesLabel = null!;
    private NumericUpDown centeredOutputHeightNumeric = null!;
    private Button centeredContentStartButton = null!;
    private Label centeredContentHelpLabel = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        layoutPanel = new TableLayoutPanel();
        calibrationLabel = new Label();
        calibrationPathTextBox = new TextBox();
        browseCalibrationButton = new Button();
        inputLabel = new Label();
        inputFolderTextBox = new TextBox();
        browseInputButton = new Button();
        outputLabel = new Label();
        outputFolderTextBox = new TextBox();
        browseOutputButton = new Button();
        placementLabel = new Label();
        placementComboBox = new ComboBox();
        recursiveCheckBox = new CheckBox();
        fixedLabel = new Label();
        fixedPanel = new FlowLayoutPanel();
        fixedXLabel = new Label();
        fixedXNumeric = new NumericUpDown();
        fixedYLabel = new Label();
        fixedYNumeric = new NumericUpDown();
        startButton = new Button();
        progressBar = new ProgressBar();
        statusLabel = new Label();
        helpLabel = new Label();
        centeredContentGroupBox = new GroupBox();
        centeredContentPanel = new FlowLayoutPanel();
        centeredInputSizeLabel = new Label();
        centeredInputWidthNumeric = new NumericUpDown();
        centeredInputTimesLabel = new Label();
        centeredInputHeightNumeric = new NumericUpDown();
        centeredOutputSizeLabel = new Label();
        centeredOutputWidthNumeric = new NumericUpDown();
        centeredOutputTimesLabel = new Label();
        centeredOutputHeightNumeric = new NumericUpDown();
        centeredContentStartButton = new Button();
        centeredContentHelpLabel = new Label();
        layoutPanel.SuspendLayout();
        fixedPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)fixedXNumeric).BeginInit();
        ((System.ComponentModel.ISupportInitialize)fixedYNumeric).BeginInit();
        centeredContentGroupBox.SuspendLayout();
        centeredContentPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)centeredInputWidthNumeric).BeginInit();
        ((System.ComponentModel.ISupportInitialize)centeredInputHeightNumeric).BeginInit();
        ((System.ComponentModel.ISupportInitialize)centeredOutputWidthNumeric).BeginInit();
        ((System.ComponentModel.ISupportInitialize)centeredOutputHeightNumeric).BeginInit();
        SuspendLayout();

        layoutPanel.AutoScroll = true;
        layoutPanel.ColumnCount = 3;
        layoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        layoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        layoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        layoutPanel.Controls.Add(calibrationLabel, 0, 0);
        layoutPanel.Controls.Add(calibrationPathTextBox, 1, 0);
        layoutPanel.Controls.Add(browseCalibrationButton, 2, 0);
        layoutPanel.Controls.Add(inputLabel, 0, 1);
        layoutPanel.Controls.Add(inputFolderTextBox, 1, 1);
        layoutPanel.Controls.Add(browseInputButton, 2, 1);
        layoutPanel.Controls.Add(outputLabel, 0, 2);
        layoutPanel.Controls.Add(outputFolderTextBox, 1, 2);
        layoutPanel.Controls.Add(browseOutputButton, 2, 2);
        layoutPanel.Controls.Add(placementLabel, 0, 3);
        layoutPanel.Controls.Add(placementComboBox, 1, 3);
        layoutPanel.Controls.Add(recursiveCheckBox, 2, 3);
        layoutPanel.Controls.Add(fixedLabel, 0, 4);
        layoutPanel.Controls.Add(fixedPanel, 1, 4);
        layoutPanel.Controls.Add(startButton, 0, 5);
        layoutPanel.Controls.Add(helpLabel, 0, 6);
        layoutPanel.Controls.Add(centeredContentGroupBox, 0, 7);
        layoutPanel.Controls.Add(progressBar, 0, 8);
        layoutPanel.Controls.Add(statusLabel, 0, 9);
        layoutPanel.Dock = DockStyle.Fill;
        layoutPanel.Padding = new Padding(18);
        layoutPanel.RowCount = 11;
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

        calibrationLabel.Anchor = AnchorStyles.Left;
        calibrationLabel.AutoSize = true;
        calibrationLabel.Text = "标定 JSON：";
        calibrationLabel.Margin = new Padding(3, 10, 12, 10);
        calibrationPathTextBox.Dock = DockStyle.Fill;
        calibrationPathTextBox.Margin = new Padding(3, 7, 8, 7);
        browseCalibrationButton.AutoSize = true;
        browseCalibrationButton.Text = "浏览…";
        browseCalibrationButton.Margin = new Padding(3, 5, 3, 5);

        inputLabel.Anchor = AnchorStyles.Left;
        inputLabel.AutoSize = true;
        inputLabel.Text = "输入文件夹：";
        inputLabel.Margin = new Padding(3, 10, 12, 10);
        inputFolderTextBox.Dock = DockStyle.Fill;
        inputFolderTextBox.Margin = new Padding(3, 7, 8, 7);
        browseInputButton.AutoSize = true;
        browseInputButton.Text = "选择…";
        browseInputButton.Margin = new Padding(3, 5, 3, 5);

        outputLabel.Anchor = AnchorStyles.Left;
        outputLabel.AutoSize = true;
        outputLabel.Text = "输出文件夹：";
        outputLabel.Margin = new Padding(3, 10, 12, 10);
        outputFolderTextBox.Dock = DockStyle.Fill;
        outputFolderTextBox.Margin = new Padding(3, 7, 8, 7);
        browseOutputButton.AutoSize = true;
        browseOutputButton.Text = "选择…";
        browseOutputButton.Margin = new Padding(3, 5, 3, 5);

        placementLabel.Anchor = AnchorStyles.Left;
        placementLabel.AutoSize = true;
        placementLabel.Text = "输出方案：";
        placementLabel.Margin = new Padding(3, 10, 12, 10);
        placementComboBox.Anchor = AnchorStyles.Left;
        placementComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        placementComboBox.Width = 210;
        recursiveCheckBox.Anchor = AnchorStyles.Left;
        recursiveCheckBox.AutoSize = true;
        recursiveCheckBox.Checked = true;
        recursiveCheckBox.Text = "包含子文件夹";

        fixedLabel.Anchor = AnchorStyles.Left;
        fixedLabel.AutoSize = true;
        fixedLabel.Text = "固定位置：";
        fixedLabel.Margin = new Padding(3, 10, 12, 10);
        fixedPanel.AutoSize = true;
        fixedPanel.Controls.Add(fixedXLabel);
        fixedPanel.Controls.Add(fixedXNumeric);
        fixedPanel.Controls.Add(fixedYLabel);
        fixedPanel.Controls.Add(fixedYNumeric);
        fixedPanel.Dock = DockStyle.Fill;
        fixedPanel.WrapContents = false;
        fixedXLabel.Anchor = AnchorStyles.Left;
        fixedXLabel.AutoSize = true;
        fixedXLabel.Text = "X";
        fixedXLabel.Margin = new Padding(3, 7, 6, 3);
        fixedXNumeric.Maximum = 1919;
        fixedXNumeric.Value = 71;
        fixedXNumeric.Width = 100;
        fixedYLabel.Anchor = AnchorStyles.Left;
        fixedYLabel.AutoSize = true;
        fixedYLabel.Text = "Y";
        fixedYLabel.Margin = new Padding(16, 7, 6, 3);
        fixedYNumeric.Maximum = 1079;
        fixedYNumeric.Value = 196;
        fixedYNumeric.Width = 100;

        layoutPanel.SetColumnSpan(startButton, 3);
        startButton.Anchor = AnchorStyles.Left;
        startButton.AutoSize = true;
        startButton.Text = "开始批量畸变矫正";
        startButton.Margin = new Padding(3, 14, 3, 10);

        layoutPanel.SetColumnSpan(progressBar, 3);
        progressBar.Dock = DockStyle.Top;
        progressBar.Height = 18;
        progressBar.Margin = new Padding(3, 4, 3, 4);

        layoutPanel.SetColumnSpan(statusLabel, 3);
        statusLabel.AutoEllipsis = true;
        statusLabel.Dock = DockStyle.Top;
        statusLabel.Text = "等待开始";
        statusLabel.Margin = new Padding(3, 5, 3, 5);

        layoutPanel.SetColumnSpan(helpLabel, 3);
        helpLabel.AutoSize = true;
        helpLabel.Dock = DockStyle.Top;
        helpLabel.ForeColor = Color.DimGray;
        helpLabel.Padding = new Padding(0, 8, 0, 0);
        helpLabel.Text = "每张输出均为 1920×1080 PNG；映射区域以外自动填黑。输出按自动位置/固定位置分目录，并保留输入子目录结构。";

        layoutPanel.SetColumnSpan(centeredContentGroupBox, 3);
        centeredContentGroupBox.AutoSize = true;
        centeredContentGroupBox.Controls.Add(centeredContentPanel);
        centeredContentGroupBox.Dock = DockStyle.Top;
        centeredContentGroupBox.Margin = new Padding(3, 16, 3, 8);
        centeredContentGroupBox.Padding = new Padding(10, 8, 10, 10);
        centeredContentGroupBox.Text = "居中矩形内容批量矫正";

        centeredContentPanel.AutoSize = true;
        centeredContentPanel.Controls.Add(centeredInputSizeLabel);
        centeredContentPanel.Controls.Add(centeredInputWidthNumeric);
        centeredContentPanel.Controls.Add(centeredInputTimesLabel);
        centeredContentPanel.Controls.Add(centeredInputHeightNumeric);
        centeredContentPanel.Controls.Add(centeredOutputSizeLabel);
        centeredContentPanel.Controls.Add(centeredOutputWidthNumeric);
        centeredContentPanel.Controls.Add(centeredOutputTimesLabel);
        centeredContentPanel.Controls.Add(centeredOutputHeightNumeric);
        centeredContentPanel.Controls.Add(centeredContentStartButton);
        centeredContentPanel.Controls.Add(centeredContentHelpLabel);
        centeredContentPanel.Dock = DockStyle.Fill;
        centeredContentPanel.Padding = new Padding(4, 5, 4, 2);
        centeredContentPanel.WrapContents = true;

        centeredInputSizeLabel.Anchor = AnchorStyles.Left;
        centeredInputSizeLabel.AutoSize = true;
        centeredInputSizeLabel.Margin = new Padding(3, 8, 5, 3);
        centeredInputSizeLabel.Text = "输入居中矩形";
        centeredInputWidthNumeric.Minimum = 32;
        centeredInputWidthNumeric.Maximum = 1920;
        centeredInputWidthNumeric.Value = 1777;
        centeredInputWidthNumeric.Width = 82;
        centeredInputTimesLabel.Anchor = AnchorStyles.Left;
        centeredInputTimesLabel.AutoSize = true;
        centeredInputTimesLabel.Margin = new Padding(4, 8, 4, 3);
        centeredInputTimesLabel.Text = "×";
        centeredInputHeightNumeric.Minimum = 32;
        centeredInputHeightNumeric.Maximum = 1080;
        centeredInputHeightNumeric.Value = 687;
        centeredInputHeightNumeric.Width = 82;

        centeredOutputSizeLabel.Anchor = AnchorStyles.Left;
        centeredOutputSizeLabel.AutoSize = true;
        centeredOutputSizeLabel.Margin = new Padding(18, 8, 5, 3);
        centeredOutputSizeLabel.Text = "输出外接尺寸";
        centeredOutputWidthNumeric.Minimum = 32;
        centeredOutputWidthNumeric.Maximum = 1920;
        centeredOutputWidthNumeric.Value = 1777;
        centeredOutputWidthNumeric.Width = 82;
        centeredOutputTimesLabel.Anchor = AnchorStyles.Left;
        centeredOutputTimesLabel.AutoSize = true;
        centeredOutputTimesLabel.Margin = new Padding(4, 8, 4, 3);
        centeredOutputTimesLabel.Text = "×";
        centeredOutputHeightNumeric.Minimum = 32;
        centeredOutputHeightNumeric.Maximum = 1080;
        centeredOutputHeightNumeric.Value = 687;
        centeredOutputHeightNumeric.Width = 82;

        centeredContentStartButton.AutoSize = true;
        centeredContentStartButton.Margin = new Padding(18, 3, 3, 3);
        centeredContentStartButton.Text = "开始居中矩形批量矫正";
        centeredContentPanel.SetFlowBreak(centeredContentStartButton, true);
        centeredContentHelpLabel.AutoSize = true;
        centeredContentHelpLabel.ForeColor = Color.DimGray;
        centeredContentHelpLabel.Margin = new Padding(3, 8, 3, 3);
        centeredContentHelpLabel.Text = "输入图须为 1920×1080；先提取正中心矩形，再完整映射到指定输出外接尺寸。使用上方标定、文件夹、输出方案和固定位置设置。";

        AutoScaleMode = AutoScaleMode.Font;
        Controls.Add(layoutPanel);
        Name = "BatchWarpPage";
        Size = new Size(780, 620);
        layoutPanel.ResumeLayout(false);
        layoutPanel.PerformLayout();
        fixedPanel.ResumeLayout(false);
        fixedPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)fixedXNumeric).EndInit();
        ((System.ComponentModel.ISupportInitialize)fixedYNumeric).EndInit();
        centeredContentGroupBox.ResumeLayout(false);
        centeredContentGroupBox.PerformLayout();
        centeredContentPanel.ResumeLayout(false);
        centeredContentPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)centeredInputWidthNumeric).EndInit();
        ((System.ComponentModel.ISupportInitialize)centeredInputHeightNumeric).EndInit();
        ((System.ComponentModel.ISupportInitialize)centeredOutputWidthNumeric).EndInit();
        ((System.ComponentModel.ISupportInitialize)centeredOutputHeightNumeric).EndInit();
        ResumeLayout(false);
    }
}
