#nullable enable
namespace DistortionCorrection.UI;

partial class ManualAdjustmentPage
{
    private System.ComponentModel.IContainer? components = null;
    private TableLayoutPanel layoutPanel = null!;
    private Label baseCalibrationLabel = null!;
    private TextBox baseCalibrationTextBox = null!;
    private Button browseBaseButton = null!;
    private Label outputCalibrationLabel = null!;
    private TextBox outputCalibrationTextBox = null!;
    private Button browseOutputButton = null!;
    private Label rotationLabel = null!;
    private NumericUpDown rotationNumeric = null!;
    private Label horizontalPerspectiveLabel = null!;
    private NumericUpDown horizontalPerspectiveNumeric = null!;
    private Label verticalPerspectiveLabel = null!;
    private NumericUpDown verticalPerspectiveNumeric = null!;
    private Label scaleLabel = null!;
    private FlowLayoutPanel scalePanel = null!;
    private Label horizontalScaleLabel = null!;
    private NumericUpDown horizontalScaleNumeric = null!;
    private Label verticalScaleLabel = null!;
    private NumericUpDown verticalScaleNumeric = null!;
    private Label offsetLabel = null!;
    private FlowLayoutPanel offsetPanel = null!;
    private Label offsetXLabel = null!;
    private NumericUpDown offsetXNumeric = null!;
    private Label offsetYLabel = null!;
    private NumericUpDown offsetYNumeric = null!;
    private FlowLayoutPanel buttonPanel = null!;
    private Button resetButton = null!;
    private Button previewButton = null!;
    private Button confirmButton = null!;
    private Button restoreDesktopButton = null!;
    private Label statusLabel = null!;
    private Label helpLabel = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        layoutPanel = new TableLayoutPanel();
        baseCalibrationLabel = new Label();
        baseCalibrationTextBox = new TextBox();
        browseBaseButton = new Button();
        outputCalibrationLabel = new Label();
        outputCalibrationTextBox = new TextBox();
        browseOutputButton = new Button();
        rotationLabel = new Label();
        rotationNumeric = new NumericUpDown();
        horizontalPerspectiveLabel = new Label();
        horizontalPerspectiveNumeric = new NumericUpDown();
        verticalPerspectiveLabel = new Label();
        verticalPerspectiveNumeric = new NumericUpDown();
        scaleLabel = new Label();
        scalePanel = new FlowLayoutPanel();
        horizontalScaleLabel = new Label();
        horizontalScaleNumeric = new NumericUpDown();
        verticalScaleLabel = new Label();
        verticalScaleNumeric = new NumericUpDown();
        offsetLabel = new Label();
        offsetPanel = new FlowLayoutPanel();
        offsetXLabel = new Label();
        offsetXNumeric = new NumericUpDown();
        offsetYLabel = new Label();
        offsetYNumeric = new NumericUpDown();
        buttonPanel = new FlowLayoutPanel();
        resetButton = new Button();
        previewButton = new Button();
        confirmButton = new Button();
        restoreDesktopButton = new Button();
        statusLabel = new Label();
        helpLabel = new Label();
        layoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)rotationNumeric).BeginInit();
        ((System.ComponentModel.ISupportInitialize)horizontalPerspectiveNumeric).BeginInit();
        ((System.ComponentModel.ISupportInitialize)verticalPerspectiveNumeric).BeginInit();
        scalePanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)horizontalScaleNumeric).BeginInit();
        ((System.ComponentModel.ISupportInitialize)verticalScaleNumeric).BeginInit();
        offsetPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)offsetXNumeric).BeginInit();
        ((System.ComponentModel.ISupportInitialize)offsetYNumeric).BeginInit();
        buttonPanel.SuspendLayout();
        SuspendLayout();

        layoutPanel.AutoScroll = true;
        layoutPanel.ColumnCount = 3;
        layoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        layoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        layoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        layoutPanel.Controls.Add(baseCalibrationLabel, 0, 0);
        layoutPanel.Controls.Add(baseCalibrationTextBox, 1, 0);
        layoutPanel.Controls.Add(browseBaseButton, 2, 0);
        layoutPanel.Controls.Add(outputCalibrationLabel, 0, 1);
        layoutPanel.Controls.Add(outputCalibrationTextBox, 1, 1);
        layoutPanel.Controls.Add(browseOutputButton, 2, 1);
        layoutPanel.Controls.Add(rotationLabel, 0, 2);
        layoutPanel.Controls.Add(rotationNumeric, 1, 2);
        layoutPanel.Controls.Add(horizontalPerspectiveLabel, 0, 3);
        layoutPanel.Controls.Add(horizontalPerspectiveNumeric, 1, 3);
        layoutPanel.Controls.Add(verticalPerspectiveLabel, 0, 4);
        layoutPanel.Controls.Add(verticalPerspectiveNumeric, 1, 4);
        layoutPanel.Controls.Add(scaleLabel, 0, 5);
        layoutPanel.Controls.Add(scalePanel, 1, 5);
        layoutPanel.Controls.Add(offsetLabel, 0, 6);
        layoutPanel.Controls.Add(offsetPanel, 1, 6);
        layoutPanel.Controls.Add(buttonPanel, 0, 7);
        layoutPanel.Controls.Add(statusLabel, 0, 8);
        layoutPanel.Controls.Add(helpLabel, 0, 9);
        layoutPanel.Dock = DockStyle.Fill;
        layoutPanel.Padding = new Padding(18);
        layoutPanel.RowCount = 10;
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

        baseCalibrationLabel.Anchor = AnchorStyles.Left;
        baseCalibrationLabel.AutoSize = true;
        baseCalibrationLabel.Text = "基础标定 JSON：";
        baseCalibrationLabel.Margin = new Padding(3, 10, 12, 10);
        baseCalibrationTextBox.Dock = DockStyle.Fill;
        baseCalibrationTextBox.Margin = new Padding(3, 7, 8, 7);
        browseBaseButton.AutoSize = true;
        browseBaseButton.Text = "浏览…";
        browseBaseButton.Margin = new Padding(3, 5, 3, 5);

        outputCalibrationLabel.Anchor = AnchorStyles.Left;
        outputCalibrationLabel.AutoSize = true;
        outputCalibrationLabel.Text = "确认后标定：";
        outputCalibrationLabel.Margin = new Padding(3, 10, 12, 10);
        outputCalibrationTextBox.Dock = DockStyle.Fill;
        outputCalibrationTextBox.Margin = new Padding(3, 7, 8, 7);
        browseOutputButton.AutoSize = true;
        browseOutputButton.Text = "另存为…";
        browseOutputButton.Margin = new Padding(3, 5, 3, 5);

        rotationLabel.Anchor = AnchorStyles.Left;
        rotationLabel.AutoSize = true;
        rotationLabel.Text = "旋转角度：";
        rotationLabel.Margin = new Padding(3, 10, 12, 10);
        rotationNumeric.Anchor = AnchorStyles.Left;
        rotationNumeric.Minimum = -15;
        rotationNumeric.Maximum = 15;
        rotationNumeric.DecimalPlaces = 2;
        rotationNumeric.Increment = 0.05M;
        rotationNumeric.Width = 120;
        rotationNumeric.AccessibleDescription = "正数顺时针，负数逆时针";

        horizontalPerspectiveLabel.Anchor = AnchorStyles.Left;
        horizontalPerspectiveLabel.AutoSize = true;
        horizontalPerspectiveLabel.Text = "左右透视：";
        horizontalPerspectiveLabel.Margin = new Padding(3, 10, 12, 10);
        horizontalPerspectiveNumeric.Anchor = AnchorStyles.Left;
        horizontalPerspectiveNumeric.Minimum = -30;
        horizontalPerspectiveNumeric.Maximum = 30;
        horizontalPerspectiveNumeric.DecimalPlaces = 1;
        horizontalPerspectiveNumeric.Increment = 0.5M;
        horizontalPerspectiveNumeric.Width = 120;
        horizontalPerspectiveNumeric.AccessibleDescription = "正数左大右小，负数左小右大";

        verticalPerspectiveLabel.Anchor = AnchorStyles.Left;
        verticalPerspectiveLabel.AutoSize = true;
        verticalPerspectiveLabel.Text = "上下透视：";
        verticalPerspectiveLabel.Margin = new Padding(3, 10, 12, 10);
        verticalPerspectiveNumeric.Anchor = AnchorStyles.Left;
        verticalPerspectiveNumeric.Minimum = -30;
        verticalPerspectiveNumeric.Maximum = 30;
        verticalPerspectiveNumeric.DecimalPlaces = 1;
        verticalPerspectiveNumeric.Increment = 0.5M;
        verticalPerspectiveNumeric.Width = 120;
        verticalPerspectiveNumeric.AccessibleDescription = "正数上大下小，负数上小下大";

        scaleLabel.Anchor = AnchorStyles.Left;
        scaleLabel.AutoSize = true;
        scaleLabel.Text = "宽高缩放：";
        scaleLabel.Margin = new Padding(3, 10, 12, 10);
        scalePanel.AutoSize = true;
        scalePanel.Controls.Add(horizontalScaleLabel);
        scalePanel.Controls.Add(horizontalScaleNumeric);
        scalePanel.Controls.Add(verticalScaleLabel);
        scalePanel.Controls.Add(verticalScaleNumeric);
        scalePanel.Dock = DockStyle.Fill;
        scalePanel.WrapContents = false;
        horizontalScaleLabel.Anchor = AnchorStyles.Left;
        horizontalScaleLabel.AutoSize = true;
        horizontalScaleLabel.Text = "宽 %";
        horizontalScaleLabel.Margin = new Padding(3, 7, 6, 3);
        horizontalScaleNumeric.DecimalPlaces = 1;
        horizontalScaleNumeric.Increment = 0.5M;
        horizontalScaleNumeric.Minimum = 50;
        horizontalScaleNumeric.Maximum = 150;
        horizontalScaleNumeric.Value = 100;
        horizontalScaleNumeric.Width = 90;
        verticalScaleLabel.Anchor = AnchorStyles.Left;
        verticalScaleLabel.AutoSize = true;
        verticalScaleLabel.Text = "高 %";
        verticalScaleLabel.Margin = new Padding(16, 7, 6, 3);
        verticalScaleNumeric.DecimalPlaces = 1;
        verticalScaleNumeric.Increment = 0.5M;
        verticalScaleNumeric.Minimum = 50;
        verticalScaleNumeric.Maximum = 150;
        verticalScaleNumeric.Value = 100;
        verticalScaleNumeric.Width = 90;

        offsetLabel.Anchor = AnchorStyles.Left;
        offsetLabel.AutoSize = true;
        offsetLabel.Text = "整体平移：";
        offsetLabel.Margin = new Padding(3, 10, 12, 10);
        offsetPanel.AutoSize = true;
        offsetPanel.Controls.Add(offsetXLabel);
        offsetPanel.Controls.Add(offsetXNumeric);
        offsetPanel.Controls.Add(offsetYLabel);
        offsetPanel.Controls.Add(offsetYNumeric);
        offsetPanel.Dock = DockStyle.Fill;
        offsetPanel.WrapContents = false;
        offsetXLabel.Anchor = AnchorStyles.Left;
        offsetXLabel.AutoSize = true;
        offsetXLabel.Text = "X px";
        offsetXLabel.Margin = new Padding(3, 7, 6, 3);
        offsetXNumeric.DecimalPlaces = 1;
        offsetXNumeric.Minimum = -500;
        offsetXNumeric.Maximum = 500;
        offsetXNumeric.Width = 90;
        offsetYLabel.Anchor = AnchorStyles.Left;
        offsetYLabel.AutoSize = true;
        offsetYLabel.Text = "Y px";
        offsetYLabel.Margin = new Padding(16, 7, 6, 3);
        offsetYNumeric.DecimalPlaces = 1;
        offsetYNumeric.Minimum = -500;
        offsetYNumeric.Maximum = 500;
        offsetYNumeric.Width = 90;

        layoutPanel.SetColumnSpan(buttonPanel, 3);
        buttonPanel.AutoSize = true;
        buttonPanel.Controls.Add(resetButton);
        buttonPanel.Controls.Add(previewButton);
        buttonPanel.Controls.Add(confirmButton);
        buttonPanel.Controls.Add(restoreDesktopButton);
        buttonPanel.Dock = DockStyle.Fill;
        buttonPanel.Margin = new Padding(0, 10, 0, 6);
        resetButton.AutoSize = true;
        resetButton.Text = "归零";
        resetButton.Margin = new Padding(3, 3, 10, 3);
        previewButton.AutoSize = true;
        previewButton.Text = "生成并投影确认图";
        previewButton.Margin = new Padding(3, 3, 10, 3);
        confirmButton.AutoSize = true;
        confirmButton.Text = "人眼确认并用于批处理";
        confirmButton.Margin = new Padding(3, 3, 10, 3);
        restoreDesktopButton.AutoSize = true;
        restoreDesktopButton.Text = "恢复原桌面";

        layoutPanel.SetColumnSpan(statusLabel, 3);
        statusLabel.AutoSize = true;
        statusLabel.Dock = DockStyle.Top;
        statusLabel.ForeColor = Color.DarkGreen;
        statusLabel.Margin = new Padding(3, 8, 3, 5);
        statusLabel.Text = "标定完成后在此进行人眼微调；所有参数同时作用于确认点阵和文件夹图片。";

        layoutPanel.SetColumnSpan(helpLabel, 3);
        helpLabel.AutoSize = true;
        helpLabel.Dock = DockStyle.Top;
        helpLabel.ForeColor = Color.DimGray;
        helpLabel.Padding = new Padding(0, 6, 0, 0);
        helpLabel.Text = "旋转：正数顺时针。左右透视：正数左大右小。上下透视：正数上大下小。旋转和透视保持最终外接宽高，只有宽/高百分比会改变外接尺寸。每次生成前都会检查越界、翻折和退化。";

        AutoScaleMode = AutoScaleMode.Font;
        Controls.Add(layoutPanel);
        Name = "ManualAdjustmentPage";
        Size = new Size(780, 620);
        layoutPanel.ResumeLayout(false);
        layoutPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)rotationNumeric).EndInit();
        ((System.ComponentModel.ISupportInitialize)horizontalPerspectiveNumeric).EndInit();
        ((System.ComponentModel.ISupportInitialize)verticalPerspectiveNumeric).EndInit();
        scalePanel.ResumeLayout(false);
        scalePanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)horizontalScaleNumeric).EndInit();
        ((System.ComponentModel.ISupportInitialize)verticalScaleNumeric).EndInit();
        offsetPanel.ResumeLayout(false);
        offsetPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)offsetXNumeric).EndInit();
        ((System.ComponentModel.ISupportInitialize)offsetYNumeric).EndInit();
        buttonPanel.ResumeLayout(false);
        buttonPanel.PerformLayout();
        ResumeLayout(false);
    }

}
